# This is a basic workflow to help you get started with Actions

name: Slack Status


on:
  push:
    branches:
      - master
jobs:

  slack_status_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
      - name: Now is
        run: |
          date
      - name: Directory content
        run: |
          ls -l