# This is a basic workflow to help you get started with Actions

name: Slack Status


on:
  push:
    branches:
      - master
jobs:

  slack_status_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
     env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      if: always() # Pick up events even if the job fails or is canceled.