# This is a basic workflow to help you get started with Actions

name: Deployment pipeline
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  
  
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  simple_slack_status:
    runs-on: ubuntu-18.04
    if: ${{github.event_name == 'push'}}
    steps:
    
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: test
        run: npm run test
      - name: build
        run: npm run build
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} 
       if: always()